### ISSUE TITLE
Setting the mode on initialization

### ISSUE THREAD

**Issue by fhunleth** [Hermanverschooten/gpio_rpi#3]
What do you think of setting the pullup/pulldown mode at initialization? For example, `GpioRpi.start_link(18, :input_pullup)`. The supported options would be `:output`, `:input`, `:input_pullup`, `:input_pulldown`. A couple reasons: 
- I like that the knowledge of an input being a pullup or pulldown is textually close to the initialization since it's such an important feature of the pin.
- The pullup and pulldown setting only affects inputs. Coupling them together with the input setting gets rid of any confusion about an output pullup being a possibility.
- It's one more thing that I can put in my supervisor's worker initialization list. I realize that having to call `set_int` means that not everything fits in the initialization list, but it would be nice to eventually fix that in `elixir_ale` as well.

As for `set_mode/2`, my feeling is that it should take `:output`, `:input`, `:input_pullup`, and `:input_pulldown` as well so that people can interact with OneWire and other non-I2c/SPI devices w/o a Linux kernel driver. I never added that to `elixir_ale` since I thought that bitbanging OneWire in Elixir wasn't interesting. It also is more interesting if there's :input_pullup support. However, recently people have told me about interfacing with some simple devices like thermometers and humidity sensors. Since configuring Linux is still relatively hard, maybe bitbanging OneWire will enable an easier route for new users.

**Comment by Hermanverschooten** [comment]
I like the idea.  I'll have a look at it, :output, :input, :input_pullup, :input_pulldown and :input_pullnone.
Then I'd also have to change the set_mode/2 to change the input/output direction.

**Comment by Hermanverschooten** [comment]
Decided to leave the set_mode/2 function alone.

**Comment by Hermanverschooten** [comment]
Moved setting the pullup to an optional parameter `:mode` and added `:interrupt` too.
This should allow to set both in the supervisor's worker initialisation.

**Comment by Hermanverschooten** [comment]
Released version 0.2.0 to cover this.
